// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  fineractPlatformTenantId: 'default',  // For connecting to server running elsewhere update the tenant identifier
  GatewayTenantId: 'default',
  GatewayApiUrl: 'https://uat.tekcompay.com:8287',
  GatewayApiUrlPrefix: '/billPos',
  baseApiUrl: 'https://uat.tekcompay.com:9443',
  apiProvider: '/fineract-provider/api',
  apiVersion: '/v1',
  serverUrl: '',
  GatewayServerUrl: '',
  oauth: {
    enabled: false,  // For connecting to Midas using OAuth2 Authentication change the value to true
    serverUrl: ''
  },
  defaultLanguage: 'vi-VN',
  supportedLanguages: [
    'en-US',
    'vi-VN'
  ],
  languagesName: {
    en: 'English',
    vi: 'Vietnamese',
  }
};

// Server URL
environment.serverUrl = `${environment.baseApiUrl}${environment.apiProvider}${environment.apiVersion}`;
environment.oauth.serverUrl = `${environment.baseApiUrl}${environment.apiProvider}`;
environment.GatewayServerUrl = `${environment.GatewayApiUrl}`;
