on:
  push:
    branches: [ staging ]

name: self-hosted-midas

jobs:
  deployStaging:
    runs-on: self-hosted
    steps:
    # checkout branch
    #- uses: actions/checkout@v2
    - name: git pull
      run: |
        cd /root/actions-runner/midas/midas_source/
        ls
        git pull origin staging
    - name: yarn install 
      run: |
        ls
        yarn install
    - name: build app 
      run: |
        ls
        ng build --prod --output-hashing=all --deleteOutputPath=true --base-href="/"  --serviceWorker=true --outputPath="/usr/share/nginx/html/staging/" 
