on: [push]

name: self-hosted-example

jobs:
  simpleExample:
    runs-on: self-hosted
    steps:
    # checkout branch
    - uses: actions/checkout@v2
    - name: yarn install, build
      run: |
        yarn install
        ng build --prod --output-hashing=all --deleteOutputPath=true --outputPath="/usr/share/nginx/html/web-app/" 